### PR TITLE
V0.1.0 rc

### PR DESCRIPTION
**Pull request by brucellino**
# Short summary of changes

This implements a role for the UMD worker node, using two other roles which have been previously tested:
- [UMD](https://github.com/EGI-foundation/ansible-role-umd)
- [VOMS Client](https://github.com/EGI-Foundation/ansible-role-voms-client)

This is the release candidate for v0.1.0 for the worker node role.

## Test coverage

Tests are implemented with TestInfra and scenarios managed with Molecule.

### Scenarios

Only the default scenario is considered The role is tested against CEntOS 6 and CEntOS7 environments. Infrastructure tests are described in `molecule/default/tests`

# Dear reviewers

This PR should already be passing on Travis, so most actual errors should be taken care of. Please consider the following when reviewing 
  1. Is the role applicable to all kinds of worker nodes?
  1. Do the variables make sense (name and structure)?
  1. Is the documentation (README and comments) adequate?
  1. Does the role deviate from the [Ansible Style Guide](https://github.com/EGI-foundation/ansible-style-guide)

Thanks!

### CODE REVIEW

**Review by gwarf — APPROVED** [review]
Looks good to me.

**Comment by brucellino** [comment]
@maarten-litmaath if you could weigh in I'd appreciate it immensely :bowing_man:

**Comment by maarten-litmaath** [comment]
Hi Bruce,
I have checked these changes that were approved by Baptiste:

https://github.com/EGI-Foundation/ansible-role-wn/pull/1/files/1b19a6ff1c215103ab11aa9ed0486ca4cb1d3f88

I do not understand why molecule/default/packages-redhat-6.txt
has a bunch of packages missing that are required by the WN meta rpm:

http://repository.egi.eu/sw/production/umd/4/sl6/x86_64/updates/emi-wn-3.1.0-1.el6.x86_64.rpm

These are absent:

c-ares
cleanup-grid-accounts
dcache-srmclient
dcap
dcap-devel
dcap-libs
dcap-tunnel-gsi
dcap-tunnel-krb
dcap-tunnel-ssl
dcap-tunnel-telnet
dpm
dpm-devel
dpm-libs
dpm-perl
dpm-python
fetch-crl
gfal2-all
gfal2-devel
gfal2-doc
gfal2-python
gfal2-util
gfalFS
ginfo
glite-yaim-core
globus-gass-copy-progs
globus-proxy-utils
gridsite-libs
lcg-ManageVOTag
lcg-info
lcg-infosites
lcg-tags
lcgdm-devel(x86-32)
lfc
lfc-devel
lfc-libs
lfc-perl
lfc-python
openldap-clients
python-ldap
uberftp
voms-clients3
voms-devel

And it has two that do not appear in the rpm dependencies:

libdpm
liblfc

For molecule/default/packages-redhat-7.txt the packages match the
corresponding meta rpm deps.

**Comment by brucellino** [comment]
@maarten-litmaath Thanks for catching that. As it turns out, the fixtures are in the actual python script because I hadn't figured out how to load them from a file before. The plan was to take the dependencies from the metapackage `spec` and keep them in change control - I suppose with a bit of plumbing, I could pull them in automatically instead of copying them in by hand. This would be more robust I think.

I think maybe we should add something to the style guide about what's the best way to have fixtures like this.

Thanks again!

**Comment by brucellino** [comment]
@maarten-litmaath I've removed the fixtures from the python file to a separate file, which will make it easier to debug and maintain. I've also verified that the ones you said were missing in https://github.com/EGI-Foundation/ansible-role-wn/pull/1#issuecomment-404312103 are asserted. Thanks again

**Pull request merged**
